variable "project_id" {}
variable "region" {}
variable "credentials_file_path" {}
variable "vpc_name" {}
variable "subnet1_name" {}
variable "subnet2_name" {}
variable "routing_mode" {}
variable "subnet1_ip_address" {}
variable "subnet2_ip_address" {}
variable "route_name" {}
variable "vm_instance_name" {}
variable "machine_type" {}
variable "vm_instance_zone" {}
variable "image_name" {}
variable "instance_size" {}
variable "instance_type" {}
variable "firewall_network" {}
variable "database_port" {}
variable "salt_rounds" {}
variable "sql_database_instance_name" {}
variable "sql_db_instance_region" {}
variable "sql_db_instance_disk_type" {}
variable "sql_db_instance_tier" {}
variable "sql_db_name" {}
variable "sql_user_name" {}
variable "sql_db_instance_availability_type" {}
variable "compute_global_address_prefix_length" {}
variable "compute_global_address_name" {}
variable "firewall_allow_ports" {}
variable "firewall_deny_ports" {}
variable "source_ranges" {}
variable "gcga_purpose" {}
variable "gcga_address_type" {}
variable "sql_instance_disk_size" {}
variable "sql_instance_deletion_protection_enabled" {}
