name: "Terraform"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_credentials_file_path: ${{ secrets.TF_VAR_CREDENTIALS_FILE_PATH }}
        run: terraform plan

      - name: Terraform Validate
        id: validate
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_credentials_file_path: ${{ secrets.TF_VAR_CREDENTIALS_FILE_PATH }}
        run: terraform validate
